### ISSUE TITLE
Drag/Drop image results in image preview

### ISSUE THREAD

**Issue by davidortinau** [johnlindquist/open-source-plugins#1]
I installed Embedder and rebooted IntelliJ. When I drag/drop PNG image(s) into an AS code file, IntelliJ shows me the image preview and doesn't generate the embed code. 

I'm running IntelliJ 10.5 Build IU 107.105

Something I may be doing wrong? Settings conflict?

**Comment by johnlindquist** [comment]
Hey David,

It doesn't support drag/drop. You have to select the file, multiple files, or dir from your project view then you the "tools->embed" or the keyboard shortcut.

Cheers,
John

**Comment by davidortinau** [comment]
Gotcha. I watched your initial video showing this and must've jumped
directly into fantasy. You inspire me. :)

On Jun 22, 2011, at 7:28 AM, johnlindquist
reply@reply.github.com
wrote:

**Comment by johnlindquist** [comment]
Heh, I think there are a lot of "cool" things we could do with this plugin (image browser, etc), but I really don't think it's worth the effort since it's so simple now.

**Comment by davidortinau** [comment]
Totally agree. I just missed the shortcut bit.

On Jun 22, 2011, at 9:07 AM, johnlindquist
reply@reply.github.com
wrote:
