### ISSUE TITLE
Robotlegs plugin broken since updating to IDEA 11.1.1

### ISSUE THREAD

**Issue by Hyperlounge** [johnlindquist/open-source-plugins#10]
Get this error:

17:43:33 NoSuchMethodError: com.intellij.find.findUsages.FindUsagesManager.processUsages(Lcom/intellij/find/findUsages/FindUsagesHandler;Lcom/intellij/util/Processor;)Lcom/intellij/usages/UsageViewPresentation;: com.intellij.find.findUsages.FindUsagesManager.processUsages(Lcom/intellij/find/findUsages/FindUsagesHandler;Lcom/intellij/util/Processor;)Lcom/intellij/usages/UsageViewPresentation;

**Comment by Hyperlounge** [comment]
Sorry - just seen the update!

**Comment by imrahil** [comment]
What update? Could you provide more info?
