### ISSUE TITLE
Robotlegs plugin suggestion

### ISSUE THREAD

**Issue by Hyperlounge** [johnlindquist/open-source-plugins#11]
Thanks for great plugin! what would make it even greater is if it could be sortable by column.

**Comment by johnlindquist** [comment]
Thanks! I've gotten very little feedback on this plugin, so I haven't put too much effort into it since its release a while ago. No guarantees of getting around to sorting the list as I haven't done much Robotlegs in a while.

**Comment by imrahil** [comment]
Sort added in latest version. Check it out :)
