### ISSUE TITLE
QuickJump: keymap reference options

### ISSUE THREAD

**Issue by geekrumper** [johnlindquist/open-source-plugins#17]
Almost all european layouts requires to press "shift+," (shift + comma) to get the "semi-colon". Doing so, will not activate the plugin at all. Allthough I'm not sure if this issue is related to IntelliJ 12:

[Issue 15](https://github.com/johnlindquist/open-source-plugins/issues/15)

But still, this feature would be nice to have, which let's any user personalize his own keys to get the job done.

**Comment by leobin** [comment]
you can change the quickjump shortcut in Preferences >> Keymap search for quickjump
